-- ============================================================
--  NEXUS OS — EXPANSÃO DE ESTOQUE (120 ITENS)
--  Cole este script no SQL Editor do seu Supabase para expandir a Loja.
-- ============================================================

-- Limpeza preventiva (Opcional: descomente se quiser resetar a loja)
-- DELETE FROM public.store_items WHERE is_for_sale = TRUE;

INSERT INTO public.store_items (name, description, category, rarity, price, item_type, damage_dice, is_for_sale, is_loot)
VALUES 
-- ── CONSUMÍVEIS (20 ITENS) ──────────────────────────────────
('Bio-Gel Regenerativo', 'Pasta acelera a cicatrização de cortes leves.', 'consumable', 'common', 45, 'Manutenção Biológica', '1d6+2', TRUE, TRUE),
('Nano-Sutura O.R.T.', 'Dispositivo portátil que fecha feridas instantaneamente.', 'consumable', 'uncommon', 150, 'Kit Médico', '2d8+4', TRUE, TRUE),
('Estimulante Neural "Focus"', 'Aumenta a percepção visual por tempo limitado.', 'consumable', 'common', 80, 'Estimulante', '1d4 SP', TRUE, TRUE),
('Pílula de Recalibragem Zero', 'Reduz o estresse mental e a exposição.', 'consumable', 'rare', 450, 'Psico-Estabilizador', '2d10 Mental', TRUE, TRUE),
('Bateria de Fusão Portátil', 'Recarrega dispositivos de energia e ferramentas.', 'consumable', 'common', 30, 'Carga', NULL, TRUE, TRUE),
('Inalador de Oxigênio Líquido', 'Essencial para ambientes sem atmosfera.', 'consumable', 'common', 25, 'Suporte de Vida', NULL, TRUE, TRUE),
('Kit de Reparo de Armadura', 'Placas de reposição rápidas para coletes.', 'consumable', 'uncommon', 200, 'Kit Técnico', '1d12 RD', TRUE, TRUE),
('Neuro-Bloqueador de Dor', 'Ignora penalidades de ferimentos graves.', 'consumable', 'uncommon', 110, 'Analéptico', '3d6 HP', TRUE, TRUE),
('Cápsula de Sono Criogênico', 'Recuperação total de HP em repouso assistido.', 'consumable', 'rare', 800, 'Sustento', 'FULL HP', TRUE, FALSE),
('Filtro de Radiação Gamma', 'Protege contra efeitos colaterais de ambientes tóxicos.', 'consumable', 'common', 60, 'Antídoto', NULL, TRUE, TRUE),
('Soro Autossuficiente v2', 'Elimina a necessidade de alimento por 24h.', 'consumable', 'common', 40, 'Nutrição', NULL, TRUE, TRUE),
('Ampola de Adrenalina Pura', 'Um último suspiro para quem está à beira do colapso.', 'consumable', 'legendary', 1200, 'Emergência', '4d10 HP', TRUE, TRUE),
('Patch de Conectividade Neural', 'Aumenta temporariamente a inteligência (INT).', 'consumable', 'uncommon', 180, 'Upgrade Temporal', '+2 INT', TRUE, TRUE),
('Esponja Hemostática', 'Para conter grandes hemorragias em campo.', 'consumable', 'common', 35, 'Médico', '1d4+1', TRUE, TRUE),
('Detector de Radiação Portátil', 'Analisa a toxicidade do ambiente próximo.', 'consumable', 'common', 90, 'Utilitário', NULL, TRUE, TRUE),
('Spray de Blindagem Iônica', 'Aumenta temporariamente a RD contra energia.', 'consumable', 'uncommon', 220, 'Defesa', '+2 RD', TRUE, TRUE),
('Pílula de Sonho Lucid', 'Aumenta a recuperação de SP durante o sono.', 'consumable', 'uncommon', 150, 'Neuro-Drogas', '+5 SP', TRUE, TRUE),
('Antitoxina Multiespectral', 'Neutraliza a maioria dos venenos biológicos.', 'consumable', 'common', 75, 'Antídoto', NULL, TRUE, TRUE),
('Cápsula de Memória RAM', 'Aumenta temporariamente a capacidade de hackear.', 'consumable', 'rare', 500, 'Hack Tool', NULL, TRUE, TRUE),
('Reagente de Carbono', 'Usado para fabricar e reparar lâminas.', 'consumable', 'common', 50, 'Material', NULL, TRUE, TRUE),

-- ── ARMADURAS (20 ITENS) ────────────────────────────────────
('Plastrom de Polímero', 'Leve e flexível, mas de baixa proteção.', 'armor', 'common', 400, 'Armadura', 'RD 1', TRUE, TRUE),
('Colete Tático O.R.T.', 'Equipamento padrão dos agentes de campo.', 'armor', 'uncommon', 950, 'Armadura', 'RD 3', TRUE, TRUE),
('Couraça de Combate Urbana', 'Pesada, mas eficiente contra disparos de médio calibre.', 'armor', 'uncommon', 1400, 'Armadura', 'RD 4', TRUE, TRUE),
('Exo-Moldura de Suporte', 'Aumenta a capacidade de carga e oferece proteção básica.', 'armor', 'rare', 2500, 'Exoesqueleto', 'RD 3', TRUE, FALSE),
('Traje de Infiltração Térmica', 'Reduz a assinatura de calor e oferece RD leve.', 'armor', 'rare', 3200, 'Armadura', 'RD 2', TRUE, TRUE),
('Placa de Cerâmica Blindada', 'Proteção especializada contra projéteis cinéticos.', 'armor', 'uncommon', 1100, 'Armadura', 'RD 5', TRUE, TRUE),
('Casaco de Couro Sintético', 'Estilo e uma leve proteção contra facas.', 'armor', 'common', 250, 'Armadura', 'RD 1', TRUE, TRUE),
('Traje Espacial Reforçado', 'Proteção completa contra o vácuo e micro-meteoritos.', 'armor', 'rare', 4000, 'Armadura', 'RD 4', TRUE, FALSE),
('Armadura de Placas de Titânio', 'A escolha ideal para quem não se importa com o peso.', 'armor', 'legendary', 8500, 'Armadura', 'RD 8', TRUE, FALSE),
('Colete de Aramida de Malha', 'Discreto e resistente a cortes.', 'armor', 'common', 550, 'Armadura', 'RD 2', TRUE, TRUE),
('Escafandro de Mineração', 'Extremamente pesado, mas virtualmente indestrutível.', 'armor', 'uncommon', 1800, 'Armadura', 'RD 6', TRUE, TRUE),
('Traje de Biossegurança Nível 4', 'Protege contra riscos biológicos e químicos.', 'armor', 'rare', 2100, 'Armadura', 'RD 2', TRUE, TRUE),
('Manto do Guardião do Tempo', 'Tecido reforçado com fibras temporais.', 'armor', 'legendary', 12000, 'Armadura', 'RD 5', TRUE, FALSE),
('Armadura de Choque Elétrico', 'Libera descarga após ataques recebidos.', 'armor', 'rare', 5000, 'Armadura', 'RD 4', TRUE, FALSE),
('Exo-Armadura Goliath', 'O ápice da tecnologia defensiva móvel.', 'armor', 'legendary', 25000, 'Exoesqueleto', 'RD 12', TRUE, FALSE),
('Colete de Kevlar Militar', 'Versão reforçada do colete padrão corporativo.', 'armor', 'uncommon', 1200, 'Armadura', 'RD 4', TRUE, TRUE),
('Sobretudo com Fibras de Vidro', 'Proteção moderada contra armas de energia.', 'armor', 'uncommon', 1300, 'Armadura', 'RD 3', TRUE, TRUE),
('Placas de Reação Ativa', 'Destruídas para anular um único dano massivo.', 'armor', 'rare', 3500, 'Armadura', 'RD 10 (1 uso)', TRUE, TRUE),
('Blindagem Iônica Portátil', 'Gera um pequeno campo de força ao redor do peito.', 'armor', 'rare', 6500, 'Escudo Energético', 'RD 6', TRUE, FALSE),
('Traje de Treinamento de Recruta', 'Simples e funcional para novos agentes.', 'armor', 'common', 150, 'Armadura', 'RD 1', TRUE, TRUE),

-- ── ARMAS BRANCAS (20 ITENS) ────────────────────────────────
('Punhal de Carbono', 'Corte precisos e rápidos. Fácil de esconder.', 'weapon', 'common', 120, 'Arma Branca', '1d4+1', TRUE, TRUE),
('Bastão Telescópico', 'Arma não letal eficiente para imobilização.', 'weapon', 'common', 80, 'Arma Branca', '1d6', TRUE, TRUE),
('Machado de Incêndio Moderno', 'Lâmina pesada com quebra-vidros.', 'weapon', 'common', 200, 'Arma Branca', '1d8', TRUE, TRUE),
('Katar de Energia', 'Lâminas gêmeas que vibram em alta frequência.', 'weapon', 'uncommon', 450, 'Arma Branca', '1d6+3', TRUE, TRUE),
('Catarana Monomolecular', 'Corta através de quase qualquer material biológico.', 'weapon', 'rare', 1200, 'Arma Branca', '2d6', TRUE, TRUE),
('Mace Elétrica', 'Emite descarga alta ao impactar o alvo.', 'weapon', 'uncommon', 550, 'Arma Branca', '1d8+2', TRUE, TRUE),
('Faca de Pescoço Discreta', 'Para situações em que você foi desarmado.', 'weapon', 'common', 50, 'Arma Branca', '1d4', TRUE, TRUE),
('Martelo Gravitacional', 'Lento, mas o impacto gera uma onda de choque.', 'weapon', 'legendary', 3500, 'Arma Branca', '3d6+4', TRUE, FALSE),
('Chicotet Elétrico', 'Alcance médio para uma arma branca.', 'weapon', 'rare', 900, 'Arma Branca', '1d10', TRUE, TRUE),
('Espada Curta Ionizada', 'Especializada contra drones e sintéticos.', 'weapon', 'uncommon', 600, 'Arma Branca', '1d8+3', TRUE, TRUE),
('Soco Inglês com Espinhos', 'Para quem prefere resolver as coisas de perto.', 'weapon', 'common', 40, 'Arma Branca', '1d4+2', TRUE, TRUE),
('Lâmina Oculta de Pulso', 'Sempre pronta para o abate furtivo.', 'weapon', 'rare', 1500, 'Arma Branca', '1d10', TRUE, FALSE),
('Adaga Ritualística de Chronos', 'Diz a lenda que corta o próprio tempo.', 'weapon', 'legendary', 5000, 'Arma Branca', '2d8+5', TRUE, FALSE),
('Foice de Colheita de Almas', 'Utilizada por facções renegadas do setor vago.', 'weapon', 'rare', 2200, 'Arma Branca', '2d10', TRUE, TRUE),
('Bastão de Choque Policial', 'Padrão das forças de segurança de Porto Estelar.', 'weapon', 'common', 150, 'Arma Branca', '1d6+1', TRUE, TRUE),
('Garra de Combate "Predador"', 'Aumenta a letalidade do combate desarmado.', 'weapon', 'uncommon', 400, 'Arma Branca', '1d8', TRUE, TRUE),
('Lança Cinética', 'Pode ser lançada ou usada em combate próximo.', 'weapon', 'uncommon', 750, 'Arma Branca', '1d12', TRUE, TRUE),
('Cimitarra do Deserto de Vidro', 'Forjada em calor extremo, extremamente afiada.', 'weapon', 'rare', 1100, 'Arma Branca', '2d6+2', TRUE, TRUE),
('Sabre de Luz (Réplica)', 'Brinquedo? Nem tanto, queima ao contato.', 'weapon', 'common', 300, 'Arma Branca', '1d6', TRUE, TRUE),
('Taco de Beisebol Reforçado', 'Simples, direto e brutal.', 'weapon', 'common', 30, 'Arma Branca', '1d6', TRUE, TRUE),

-- ── ARMAS DE PEQUENO PORTE (20 ITENS) ───────────────────────
('Pistola Magnética M1', 'Tecnologia Gauss em formato compacto.', 'weapon', 'uncommon', 450, 'Arma de Pequeno Porte', '1d10', TRUE, TRUE),
('SMG "Wasp"', 'Altíssima cadência de tiro, pouco recuo.', 'weapon', 'uncommon', 600, 'Arma de Pequeno Porte', '2d4', TRUE, TRUE),
('Revolver .44 "Justice"', 'Para quem acredita que poder de parada é tudo.', 'weapon', 'common', 350, 'Arma de Pequeno Porte', '1d8+2', TRUE, TRUE),
('Pistola de Dardos Tóxicos', 'Silenciosa e mortal para alvos orgânicos.', 'weapon', 'rare', 850, 'Arma de Pequeno Porte', '1d4 + Veneno', TRUE, TRUE),
('Flare Gun Especializada', 'Ilumina e causa chamas ao impactar.', 'weapon', 'common', 150, 'Arma de Pequeno Porte', '1d6 Fogo', TRUE, TRUE),
('Derringer de Bolso', 'Uma única chance, mas de curtíssima distância.', 'weapon', 'common', 100, 'Arma de Pequeno Porte', '1d12', TRUE, TRUE),
('Pistola de Energia "Spark"', 'Recarrega sozinha se deixada ao sol.', 'weapon', 'common', 300, 'Arma de Pequeno Porte', '1d6', TRUE, TRUE),
('SMG Silenciada "Ghost"', 'O barulho do tiro é menor que o do impacto.', 'weapon', 'rare', 1100, 'Arma de Pequeno Porte', '1d8+1', TRUE, TRUE),
('Canhão de Mão "Breaker"', 'Quase um canhão, mas cabe no seu coldre.', 'weapon', 'rare', 1600, 'Arma de Pequeno Porte', '2d10', TRUE, FALSE),
('Pistola de Laser de Pulso', 'Feixe contínuo de luz concentrada.', 'weapon', 'uncommon', 550, 'Arma de Pequeno Porte', '1d8 (Energia)', TRUE, TRUE),
('Auto-Pistola de "Burst"', 'Dispara rajadas de 3 tiros.', 'weapon', 'uncommon', 700, 'Arma de Pequeno Porte', '2d6', TRUE, TRUE),
('Eletro-Stunner de Longo Alcance', 'Incapacita o alvo sem causar dano letal.', 'weapon', 'common', 250, 'Arma de Pequeno Porte', 'Paralisia', TRUE, TRUE),
('Pistola de Preços Variáveis', 'O dano aumenta conforme seu saldo em conta (lore).', 'weapon', 'legendary', 5000, 'Arma de Pequeno Porte', 'Variable', TRUE, FALSE),
('Mini-Lança-Granadas', 'Compacto, dispara pequenas ogivas explosivas.', 'weapon', 'rare', 1800, 'Arma de Pequeno Porte', '2d8 Área', TRUE, FALSE),
('Pistola de Radiação "Chernobyl"', 'Causa dano persistente por radiação.', 'weapon', 'rare', 2100, 'Arma de Pequeno Porte', '1d6 + Contaminação', TRUE, TRUE),
('Pistola Gravitacional', 'Puxa o alvo para mais perto do disparo.', 'weapon', 'rare', 2800, 'Arma de Pequeno Porte', '1d10 (Gravity)', TRUE, FALSE),
('Revólver de Laser "Centurion"', 'Visual clássico com tecnologia futurista.', 'weapon', 'uncommon', 650, 'Arma de Pequeno Porte', '1d8+3', TRUE, TRUE),
('SMG de Íons "Storm"', 'Destaque no combate contra escudos energéticos.', 'weapon', 'rare', 1400, 'Arma de Pequeno Porte', '1d12 (Ions)', TRUE, TRUE),
('Pistola Balística "Iron"', 'Construída para nunca falhar em desertos.', 'weapon', 'common', 280, 'Arma de Pequeno Porte', '1d8', TRUE, TRUE),
('Caneta Disparadora de Emergência', 'Disfarçada, dispara um único projétil de 9mm.', 'weapon', 'uncommon', 500, 'Arma de Pequeno Porte', '1d6', TRUE, FALSE),

-- ── ARMAS DE MÉDIO PORTE (20 ITENS) ─────────────────────────
('Rifle de Assalto A-10', 'O cavalo de batalha da infantaria moderna.', 'weapon', 'common', 900, 'Arma de Médio Porte', '2d8', TRUE, TRUE),
('Escopeta de Combate "Breach"', 'Devastadora em ambientes fechados.', 'weapon', 'uncommon', 1100, 'Arma de Médio Porte', '3d6 (Curto)', TRUE, TRUE),
('Rifle de Precisão "Falcon"', 'Semiautomático com ótima estabilidade térmica.', 'weapon', 'uncommon', 1500, 'Arma de Médio Porte', '2d10', TRUE, TRUE),
('Carabina de Plasma "Cutter"', 'Derrete blindagens leves com facilidade.', 'weapon', 'rare', 2800, 'Arma de Médio Porte', '3d8', TRUE, TRUE),
('Rifle de Caça Magnético', 'Para caçar feras em planetas inóspitos.', 'weapon', 'uncommon', 1300, 'Arma de Médio Porte', '2d12', TRUE, TRUE),
('Besta Elétrica Moderna', 'Silenciosa e com projéteis recuperáveis.', 'weapon', 'common', 600, 'Arma de Médio Porte', '1d10+2', TRUE, TRUE),
('Fuzil de Raios "Gamma"', 'Causa danos internos severos e invisíveis.', 'weapon', 'rare', 3500, 'Arma de Médio Porte', '2d10 (Radiation)', TRUE, TRUE),
('Lança-Chamas Portátil', 'Limpa corredores e causa pânico.', 'weapon', 'rare', 2600, 'Arma de Médio Porte', '2d8 Fogo (DOT)', TRUE, TRUE),
('Rifle de Sniper "Void"', 'Utiliza munição de antimatéria estável.', 'weapon', 'legendary', 9000, 'Arma de Médio Porte', '3d12+10', TRUE, FALSE),
('Escopeta Semiautomática "Crowd"', 'Para controle de distúrbios civis e hordas.', 'weapon', 'uncommon', 1600, 'Arma de Médio Porte', '2d8 Área', TRUE, TRUE),
('Rifle de Assalto Bullpup "Viper"', 'Compacto e preciso, ideal para ambientes urbanos.', 'weapon', 'uncommon', 1250, 'Arma de Médio Porte', '2d8+2', TRUE, TRUE),
('Fuzil de Micro-ondas', 'Aquece os fluidos corporais do alvo.', 'weapon', 'rare', 3100, 'Arma de Médio Porte', '3d6 (Energy)', TRUE, TRUE),
('Rifle de Flechettes Magnético', 'Atravessa múltiplos alvos em linha reta.', 'weapon', 'rare', 4200, 'Arma de Médio Porte', '2d10 (Penetration)', TRUE, FALSE),
('Lançador de Redes de Contenção', 'Para capturas vivas de alvos de alto valor.', 'weapon', 'uncommon', 850, 'Arma de Médio Porte', 'Containment', TRUE, TRUE),
('Rifle de Injeção Química', 'Aplica debuffs massivos conforme o disparo.', 'weapon', 'rare', 2400, 'Arma de Médio Porte', '1d8 + Debuff', TRUE, TRUE),
('Carabina de Pulso Magnético (EMP)', 'Neutraliza eletrônicos em uma pequena área.', 'weapon', 'rare', 3300, 'Arma de Médio Porte', 'EMP Shock', TRUE, TRUE),
('Rifle de Assalto Clássico M16', 'Relíquia recuperada de silos antigos.', 'weapon', 'common', 750, 'Arma de Médio Porte', '2d6+2', TRUE, TRUE),
('Espingarda de Cano Duplo "Classic"', 'Brutalidade simples e analógica.', 'weapon', 'common', 400, 'Arma de Médio Porte', '2d10', TRUE, TRUE),
('Rifle "Harpoon" Subaquático', 'Eficiente dentro e fora d''água.', 'weapon', 'uncommon', 1000, 'Arma de Médio Porte', '1d12', TRUE, TRUE),
('Fuzil de Fotons O.R.T.', 'Emite luz densa que cega e queima.', 'weapon', 'legendary', 7500, 'Arma de Médio Porte', '3d10', TRUE, FALSE),

-- ── ARMAS DE GRANDE PORTE (20 ITENS) ────────────────────────
('Metralhadora Rotativa GAU-8', 'Chuva de chumbo em alta velocidade.', 'weapon', 'rare', 4500, 'Arma de Grande Porte', '4d8', TRUE, FALSE),
('Canhão de Plasma Pesado', 'Capaz de desintegrar veículos blindados.', 'weapon', 'rare', 6000, 'Arma de Grande Porte', '5d10', TRUE, FALSE),
('Lança-Mísseis "Stinger"', 'Trava no alvo e garante o impacto.', 'weapon', 'rare', 5500, 'Arma de Grande Porte', '4d12 Explosivo', TRUE, FALSE),
('Rifle de Trilho (Railgun)', 'Projétil em Mach 7. Cruza o mapa inteiro.', 'weapon', 'legendary', 15000, 'Arma de Grande Porte', '6d12', TRUE, FALSE),
('Lança-Granadas de Tambor', 'Seis explosões rápidas para limpar o setor.', 'weapon', 'uncommon', 3200, 'Arma de Grande Porte', '3d10 Área', TRUE, TRUE),
('Canhão Sônico de Desintegração', 'Desfaz a coesão molecular do alvo.', 'weapon', 'legendary', 18000, 'Arma de Grande Porte', '7d10', TRUE, FALSE),
('Metralhadora Pesada "Browning" v2', 'Munição incendiária de alto calibre.', 'weapon', 'uncommon', 3800, 'Arma de Grande Porte', '4d6+5', TRUE, TRUE),
('Lançador de Singularidade', 'Cria um mini buraco negro que suga e implode.', 'weapon', 'legendary', 50000, 'Arma de Grande Porte', '10d10 (Void)', TRUE, FALSE),
('Canhão Térmico de Fusão', 'O alvo continua queimando por minutos.', 'weapon', 'rare', 7200, 'Arma de Grande Porte', '4d10 Fogo', TRUE, TRUE),
('Metralhadora de Laser Gatling', 'Feixes contínuos para supressão absoluta.', 'weapon', 'rare', 8500, 'Arma de Grande Porte', '5d8 (Energy)', TRUE, FALSE),
('Obuseiro Portátil de Elétron', 'Disparo lento, mas área de efeito gigantesca.', 'weapon', 'rare', 9000, 'Arma de Grande Porte', '6d8 (Eletron)', TRUE, FALSE),
('Rifle de Prótons "Ghostbuster"', 'Eficaz contra entidades espectrais e energia.', 'weapon', 'legendary', 14000, 'Arma de Grande Porte', '5d12', TRUE, FALSE),
('Lança-Mísseis Quádruplo', 'Fogo de barragem para saturação de área.', 'weapon', 'rare', 11000, 'Arma de Grande Porte', '3d12 (x4)', TRUE, FALSE),
('Sniper de Artilharia de Longo Alcance', 'Requer suporte para ser disparada.', 'weapon', 'rare', 9500, 'Arma de Grande Porte', '5d12+20', TRUE, FALSE),
('Canhão de Pulso Criogênico', 'Congela instantaneamente tanques e porta-aviões.', 'weapon', 'legendary', 22000, 'Arma de Grande Porte', 'Freeze Area', TRUE, FALSE),
('Metralhadora de Plasma "Vulcan"', 'Arma de mestre-de-fogo, consome muita energia.', 'weapon', 'rare', 13000, 'Arma de Grande Porte', '6d10', TRUE, FALSE),
('Lançador de Minas Magnéticas', 'Cria um campo minado no campo de batalha.', 'weapon', 'uncommon', 4000, 'Arma de Grande Porte', '3d10 Mine', TRUE, TRUE),
('Serra Elétrica Industrial Gigante', 'Para combates corporais de escala colossal.', 'weapon', 'uncommon', 2500, 'Arma de Grande Porte', '5d6 Melee', TRUE, TRUE),
('Canhão de Frequência "Omega"', 'Capaz de derrubar bases espaciais pequenas.', 'weapon', 'legendary', 100000, 'Arma de Grande Porte', 'OHK Possible', TRUE, FALSE),
('Rifle Pesado de Caça Orbital', 'Projetado para abater feras gigantes.', 'weapon', 'rare', 8800, 'Arma de Grande Porte', '5d12', TRUE, TRUE)
ON CONFLICT DO NOTHING;
